services:
  mint-redis:
    image: redis:8.0
    ports:
      - 6379:6379
    volumes:
      - mint-data:/data
    container_name: mint-redis
  mint-frontend:
    image: ghcr.io/mrc-ide/mint-frontend:${FRONTEND_REF:-main}
    pull_policy: always
    ports:
      - 127.0.0.1:3000:3000
    environment:
      - REDIS_URL=redis://mint-redis:6379
      - PUBLIC_MINTR_URL=http://mintr:8888
      - ORIGIN=http://127.0.0.1:3000
    depends_on:
      mint-redis:
        condition: service_started
      mintr:
        condition: service_healthy
        restart: true
  mintr:
    image: ghcr.io/mrc-ide/mintr:${API_REF:-main}
    container_name: mintr
    healthcheck:
      test: curl -f http://localhost:8888/ || exit 1
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 30s
      retries: 5
    ports:
      - 8888:8888
volumes:
  mint-data:
