name: test workflow
on:
    push:
        branches:
            - main
            - "releases/*"
    pull_request:
        branches:
            - "*"
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5
        strategy:
            matrix:
                node-version: [22.x]
